apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_name}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${cluster_issuer_email}
    privateKeySecretRef:
      name: ${cluster_issuer_name}-key
    solvers:
      - http01:
          ingress:
            class: nginx
